export const PERMISSIONS = [
  'organization.read',
  'organization.update',
  'user.create',
  'user.read',
  'user.update',
  'employee.read',
  'employee.manage',
  'role.read',
  'role.create',
  'role.update',
  'permission.read',
  'shift.read',
  'shift.create',
  'shift.update',
  'shift.assign',
  'attendance.clock_in.self',
  'attendance.clock_out.self',
  'attendance.break.manage.self',
  'attendance.read.self',
  'attendance.read.team',
  'attendance.read.organization',
  'attendance.adjust',
  'attendance.approve',
  'attendance.lock',
  'policy.read',
  'policy.manage',
  'media.upload.self',
  'media.read.self',
  'media.read.organization',
  'audit.read.organization',
  'audit.export',
  'report.read'
] as const;

export const ROLE_PERMISSION_BUNDLES: Record<string, string[]> = {
  'Organization Admin': [...PERMISSIONS],
  Manager: [
    'organization.read',
    'employee.read',
    'shift.read',
    'shift.create',
    'shift.update',
    'shift.assign',
    'attendance.read.team',
    'attendance.read.organization',
    'attendance.approve',
    'policy.read',
    'media.read.organization',
    'audit.read.organization',
    'report.read'
  ],
  Employee: [
    'organization.read',
    'attendance.clock_in.self',
    'attendance.clock_out.self',
    'attendance.break.manage.self',
    'attendance.read.self',
    'media.upload.self',
    'media.read.self',
    'shift.read',
    'policy.read'
  ],
  Auditor: ['organization.read', 'employee.read', 'attendance.read.organization', 'media.read.organization', 'audit.read.organization', 'report.read']
};
